adobe/helix-rum-enhancer

src/index.js

https://web.dev/inp/ has been promoted from experimental metric to pending metric and will replace FID within a year

feat(cwv): add INP (Interaction to next paint) as default metric

---

.gitignore
src/index.js

ping:cwv was throwing `Uncaught TypeError: window.webVitals[name] is not a function`

fix(cwv): window.webVitals[name] is not a function

---

README.md
src/index.js

61 - Add referrer detection

---

src/index.js

feat(index): enable configurable base url

---

src/index.js

https://github.com/adobe/helix-rum-js/issues/102 

feat(cwv): add support for TTFB

---

src/index.js

https://github.com/adobe/helix-rum-js/issues/103

feat(checkpoint): introduce new resource checkpoint

---

src/index.js

https://github.com/adobe/helix-rum-js/issues/103

chore: filter loadresource checkpoint by same origin

---

README.md

docs(readme): fix viewmedia checkpoint typo

---

src/index.js

fix(navigate): do not navigate on load

---

src/index.js

https://github.com/adobe/helix-rum-js/issues/120

feat: add support for source/target data attributes

---

src/index.js

fix: correct prefix check for relative urls in targets. fixes #102

---

src/index.js

fix(cwv): report metrics eagerly

---

src/index.js

Reflecting the change from #108 into the `main` branch.  

feat(sourceselector): highlight clicks on buttons and CTAs

---

src/index.js

fix: enable eager cwv reporting for revolt

---

src/index.js

fix: remove conflicting variables

---

src/index.js

feat: report source and target along with lcp event

---

src/index.js

feat: report source and target along with lcp element

---

src/index.js

adapted to v1.x branch from 2a733b3
#148
#147

feat: add logic to capture target from wrapping anchor tag (v1.x)

---

package-lock.json
src/index.js

feat: add logic to capture target from wrapping anchor tag

---

src/index.js

fix: make targetselector null safe

---

src/index.js

fix: no lcp target text from missing element

---

src/index.js

Enhancer may raise exceptions if it is not correctly setup or in some corner cases. This PRs aims to prevent propagating any error thrown by the rum enhancer.

catch potential exceptions and errors

---

src/index.js

fix: no type leads to empty checkpoint (1x)

---

src/index.js

feat(checkpoint): add consent checkpoint

---

src/index.js

Track whether CMP consent banner is shown or hidden

feat(checkpoint): add consent checkpoint to 1.x

---

src/index.js

fix: enable feature flag

---

src/index.js

feat(index): introduce simple feature flag system

---

src/index.js

feat(ads): enable ads feature flag

---

.github/workflows/main.yaml
package.json

see suggestion in https://github.com/adobe/helix-rum-enhancer/pull/191#discussion_r1632775666
Sibling PR of #193

Test more browsers (1.x)

---

.github/workflows/main.yaml
package.json

see suggestion in https://github.com/adobe/helix-rum-enhancer/pull/191#discussion_r1632775666

Test on more browsers (2.x)

---

modules/defaults.js
modules/fflags.js
modules/index.js
test/unit/fflags.test.js

feat(paid): roll out the paid checkpoint for all customers

---

modules/defaults.js
modules/fflags.js
modules/index.js
test/unit/fflags.test.js

feat(email): rollout for all customers 2.x

---

.husky/pre-commit

chore: add lint hook on commit

---

modules/index.js

these are too hard to economically reproduce

test(coverage): ignore error cases in test coverage

---

modules/fflags.js
test/it/onetrust-accepted.test.html
test/it/onetrust.test.html

Picking low-hanging test-coverage fruit here
- **test(feature-flags): enable consent tracking on localhost**
- **test(onetrust): add tests for onetrust, shown and hidden**

Test Onetrust

---

.github/workflows/main.yaml

Required changes to by-pass branch protection during release.

chore: adjust release process for branch protection

---

modules/defaults.js
modules/fflags.js
modules/index.js
modules/martech.js
test/unit/fflags.test.js

I've also moved the martech-related instrumentation code into a separate module to better isolate the more frequent changes made there.

feat(onetrust): enable on all domains

---

src/index.js

Remove feature flag for onetrust tracking

feat(onetrust): enable on all domains for rum v1.x

---

.releaserc.cjs
package-lock.json
package.json
rollup.config.js

feat(release) Generate checksum of the rum enhancer on release

---

modules/dom.js
test/unit/dom.sourceSelector.buttons.test.html
test/unit/dom.sourceSelector.test.html

- adding a failing test case
For Issue: #292

feat: capturing id of form and button type inside a form

---

test/it/img.test.html
web-test-runner.config.js

- increase wait time for a randomly failing test
- remove build folder (`src`...) from coverage

chore: various admin tasks

---

modules/index.js
test/it/fromredirect.test.html

fix(redirects): use underscore in param

---

modules/index.js

feat: remove (deprecated) FID ex-CWV

---

web-test-runner.config.js

We have to include src in instrumentation since we are testing against that file in majority of our test cases.

ci: fixing coverage report

---

modules/dom.js
test/unit/dom.sourceSelector.test.html

refactor: compacting sourceSelector code

---

plugins/onetrust.js

see https://cq-dev.slack.com/archives/C07198KKQ07/p1741614225265829?thread_ts=1741102449.318609&cid=C07198KKQ07

fix(onetrust): prevent duplicate consent tracking events

---

modules/fflags.js

fix: remove ups from all resources flag

---

plugins/webcomponent.js

ref: https://cq-dev.slack.com/archives/C07198KKQ07/p1749066966905859

fix: only watch valid customelement tagnames

---

modules/fflags.js
modules/index.js
plugins/a11y.js
test/it/a11y.audience.high.test.html
test/it/a11y.audience.keyboard.test.html
test/it/a11y.audience.low.test.html
test/it/a11y.audience.medium.test.html
test/it/a11y.audience.standard.test.html
test/it/a11y.focustrap.pingpong.test.html
test/it/a11y.focustrap.sequence.test.html
test/it/a11y.focustrap.single.test.html
test/it/a11y.test.utils.js
web-test-runner.config.js

This pull request introduces a new, privacy-first accessibility plugin (a11y.js) to gather anonymous signals about user accessibility needs and detect common implementation errors.
The primary goal is to gain a better understanding of how many users rely on assistive technologies or specific browser settings for various customer projects. This data will enable us and them to make more informed decisions and build more inclusive experiences without compromising user privacy.
- **Multi-Signal Detection**: The plugin uses a combination of static and behavioral signals to build an accurate picture of user needs.
- **Audience Scoring & Reporting**: A simple scoring system categorizes users into a11y-standard, a11y-low, a11y-medium, or a11y-high audiences based on the detected signals. This is …

feat(a11y): add a new accessibility plugin to categorize audience and detect common bugs

---

.github/workflows/update-pr-description.yaml

https://test-action--helix-rum-enhancer--adobe.aem.page/test/fixtures/otsdk-with-banner.html

chore: adding an action to update the PR with test url
