- src/index.js
#67 
Add `visibilitychange` and `pagehide`  event listeners to detect when visitors are leaving a page, and introduce a `leave` checkpoint.
Things to note:
1. Only one `leave` checkpoint is sent per page view.
2. When user switches from one browser tab to another one, the `leave` checkpoint is also sent.
3. According to the some [benchmarks](https://www.speedkit.com/blog/unload-beacon-reliability-benchmarking-strategies-for-minimal-data-loss) approximately 9% of page leaves will be missed, with the combination of events we are tracking.
4. `visibilitychange` and `pagehide` events are not always properly managed in Chrome dev tools. See [bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=472282#c26). E.g. when a visitor clicks a link and goes to a different page. 
It is …
> [67] feat(checkpoint): introduce leave checkpoint

- src/index.js
- `enter` will now fire for every page open that does not come from the same origin, including direct opens - `reload` tracks reloads or opens from the same exact page 
- `back_forward` and `prerender` track what's on the tin 
- `navigate` is all on-site navigation 
in addition the `document.VisibilityState` is tracked in `target` allowing us to filter non-visible opens that are not performance critical and often throttled
> feat(navigate): refine checkpoints for `enter`, `navigate`, `reload`, `back_forward`, and `prerender`, track `visibilityState`

- CHANGELOG.md
- package.json
- src/index.js
This PR tracks CTAs automatically in order to later compute CTRs.
The rule to track a CTA is simple: 
- the element that was clicked on has a class named `button` or `cta`
> Autotrack CTAs

- src/index.js
fixes: https://github.com/adobe/helix-rum-enhancer/issues/121
`cwv` checkpoints fire eagerly after `lazy` checkpoint:
> fix(cwv): report metrics eagerly

- src/index.js
Support for:
* `sampleRUM.collectBaseURL` : base url for rum collection (POST requests)
* `sampleRUM.baseURL` : base url for extra scripts: enhancer, webvitals, etc. (GET requests)
> feat(minirum): allow different base urls for collection and extra scripts

- src/index.js
> fix: make targetselector null safe

- src/index.js
The utm_term is typically populated from search queries and can theoretically leak PII. So it's safest to exclude it from collection for now
Fix #153
> fix(backport): exclude utm_term from collection

- src/index.js
The `utm_term` is typically populated from search queries and can theoretically leak PII. So it's safest to exclude it from collection for now
Fix #153
> fix: exclude utm_term from collection

- src/index.js
> fix: no lcp target text from missing element

- src/index.js
The feature (https://github.com/GoogleChrome/web-vitals?tab=readme-ov-file#report-the-value-on-every-change) has been tested on blog.adobe.com and revolt.tv for a couple a weeks. On those 2 sites, we could observe an increase of reported number of LCP and CLS checkpoints in the RUM data. In some cases, it is up to 4x times more reported LCP events!
- LCP
- there is only a trivial number (less than 1%) of extra requests (like 2 LCPs captured)
- CLS
- this changes how the CLS is collected - every CLS event will fire a request (while aggregated before) - before the change, we saw 9% of sessions where CLS was captured multiple times. This number now goes to 25%. Nothing critical, just a little bit more entries to be filtered out in the data reporting.
I think it is time to enable the feature …
> feat: enable reportAllChanges for all projects

- src/index.js
I think the `addEnterLeaveTracking` logic is incorrect and we do not track enough data:
- `navigate(document.referrer);` is always called (line 172), i.e. `type` is always undefined
- test `if (type !== 'navigate')` is always true when `type` is undefined`. `sampleRUM(type, payload)` is always called with an empty `checkpoint`.
`enter` will then be equal to `pageload`.
I am not fully sure this is the expected tracking behavior because it also goes through the PerformanceObserver.
@trieloff @chicharr WDTY ?
> fix: no type leads to empty checkpoint

- src/index.js
> feat(index): add new feature flag system

- src/index.js
> fix: no this in arrow functions (#182)

- src/index.js
Not sure why `headers` is pased, it is not part of the method signature (see https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon).
`body` is a string, no need to wrap into a blob.
This fixes the CORS issues.
> fix: avoid CORS

- src/index.js
Since there is no test, I do not know what the `sanitizeURL` may have been used for... but several things wrong with that code:
- the `sanitizeURL` property is set with a function (function not executed...)
- the `sanitizeURL` property is filter out because it is not in the `KNOWN_PROPERTIES`
Conclusion: no `sanitizeURL` but also no `referer`
> fix: add referer

- src/utils.js
- test/unit/utils.test.js
Basic function with a lot of issues:
- need a parameter to make it testable
- weird `path` implementation
- is `path` supposed to return the query parameters or not ?
@chicharr @trieloff please check the implementation fixes... only the `path` function is used in the code (can be overriden via a variable). I tested the code with a sample page, only the path (with no query param) is sent now (before was the url) and it is correctly processed by the collector.
> fix: correct urlSanitizers implementation

- modules/utils.js
- test/it/utils.urlSanitizers.test.html
- test/unit/utils.test.js
I changed `path` implementation to return... the url pathname while it was expected to return the origin + pathame (no query param)
> fix: restore original path behavior

- modules/dom.js
- test/unit/dom.sourceSelector.buttons.test.html
- test/unit/dom.sourceSelector.test.html
- test/unit/dom.test.js
Fix #204 by adding more logic to try to compute a selector to identify the (clicked) button. Probably not perfect but should at least cover the onetrust popup and some basic dom combo.
> feat: add more logic to button selector

- src/index.js
I can see `null` source in the data. Applying the same to `target` to be sure.
> fix: LCP source can be null

- modules/index.js
see https://helpx.adobe.com/legal/product-descriptions/aem-cloud-service.html
> feat(loadresource): include API calls in `loadresouce` requests for content request counting

- README.md
- modules/defaults.js
- modules/index.js
- test/it/navigation.test.html
as requested in https://github.com/adobe/helix-rum-enhancer/pull/257#discussion_r1718152824 the `leave` checkpoint
is no longer processed by the rum collector, so we can do without it. This reverts https://github.com/adobe/helix-rum-enhancer/commit/33abd03947b0345200eea1d5857b72a036c09923
> fix(navigation): remove `leave` checkpoint

- .husky/pre-commit
- modules/index.js
- test/it/fromrum.test.html
- test/it/img.delayed.test.html
- test/it/img.test.html
- test/it/navigation.test.html
- test/it/viewblock.delayed.test.html
- test/it/viewblock.test.html
Fix https://github.com/adobe/helix-rum-enhancer/issues/225
Thanks to @trieloff, we have now a good test coverage, I feel more confident that this does not break everything. Changed the MutationObserver logic to listen to all changes and start observing newly added assets.
> feat: observe all mutations to capture late added medias

- modules/fflags.js
- modules/index.js
- test/it/index.test.html
- test/it/navigation.test.html
source being the lang attribute of the html and target being navigator.language
see https://cq-dev.slack.com/archives/C07198KKQ07/p1725350425871959 depends on https://github.com/adobe/helix-rum-collector/pull/387
> feat(checkpoints): add support for the `language` checkpoint

- modules/dom.js
- modules/index.js
- modules/martech.js
- modules/utils.js
Decrease total size (less than 16kB) without losing readability.
> refactor(modules): minify code without losing readability

- modules/index.js
- web-test-runner.config.js
Address the collection part of https://github.com/adobe/aem-lib/issues/101
Will then require Explorer adjustments.
This PR only changes the current behaviour for the pre-rendered pages:
- fires a `prerender` checkpoint when a page is pre-rendered by the speculation engines - target will always be `hidden`
- fires a `navigate` checkpoint with `target=prerendered` when page is "activated".
`navigate` will then have 3 possible targets:
1. `visible`- default navigation
2. `hidden` - background tab
3. `prerendered` - pre-rendered pages
> feat: handle pre-speculation rules and rendering

- test/it/click.test.html
Refactor existing test and add a test for validate the click is captured even when an `a` element is added after the loading sequence.
> chore: add test for late added anchor and click checkpoint

- .renovaterc.json
Use new helix-bot capability (see https://github.com/adobe/helix-bot/issues/1573) to ignore psi check if renovate makes a PR on dev dependency.
> chore: renovate PR on dev dep do not trigger psi check

- modules/index.js
- test/it/navigation.enter.test.html
We observe bundles with multiple `enter` and `reload` checkpoints. While this does not seem to be critical, it is not necessary to post them twice.
Background: for unknown reason, the PerformanceObserver captures the events twice. The buffering seems to be the root cause but disabling the buffering might lead to losing some of the events.
> fix: do not process duplicate navigation checkpoints

- modules/index.js
- test/it/click.test.html
- test/it/index.test.html
- test/it/size.test.html
We've identify cases where several thousands of `click` checkpoints are tracked. The `click` handler is pretty straight forward (a simple `document.addEventListener('click'...)`) thus it does not seem to be a code logic issue but rather a browser / project code issue: for some reason, the browser starts firing many repeating `click` events on the same element.
This PR addresses the collection issue: do not track 2 consecutive `click` events on the same element. While this should have low impact on the use cases we want to track, I have identified one: clicks on a toggle button to open and close a menu or an accordion. The element tends to be the same. We'll lost some clicks here. But on the other hand, tracking the 2 identical clicks does not bring much neither, no clue to know how many …
> fix: do not track repeating clicks

- modules/index.js
the target field was until now unused. this change uses it for the status code and in turn tracks all errored resources as `missingresource`
> feat(missingresource): report all resource error with http status code

- modules/index.js
- test/it/fill.test.html
> fix: do not trigger fill checkpoint for hidden fields

- modules/index.js
- package-lock.json
- test/it/click.test.html
If the end users are clicking on an element repetitively, it typically indicates a problem like broken experience, confusing UI etc. https://github.com/adobe/helix-rum-enhancer/pull/339 introduced to not to track the repeating clicks, because of which we won't be able to find some of the issues faced by users. 
Currently, PSS considers if the user is clicking 10 times on the same selector with in the same session, we'll record as a rageclick (naming is little different in PSS) and based on such instances, we'll create an opportunity for our customers to fix. For PSS to continue to find these blind clicks and help our customers, we'd like to have the repeating clicks collected as valid RUM checkpoints. 
This PR will introduce the flood control to limit the max events collection to 1024. …
> fix: Implement flood control with 1024 max events

- .renovaterc.json
helix-rum-enhancer is not an "helix" project anymore, we do not use the delivery mechanism (see https://github.com/adobe/helix-rum-js/pull/215). I disabled the AEM Sync, i.e. the PSI check should not come in anymore. The label on renovate PRs is then not useful anymore...
> chore: ignore psi check not needed

- modules/dom.js
- test/it/fill.test.html
- test/unit/dom.test.js
For Click/Fill checkpoints within the form, the form information was getting lost (if it doesn't have a valid class). The information is present with the viewblock and formsubmit checkpoint, so to map the click/fill events with formsubmit and formview had some issues. This PR tries to fix that.
> feat: add class in source  selector

- plugins/onetrust.js
- test/it/onetrust-suppressed.test.html
- test/it/onetrust.test.html
Support different DOM structures of domains using OneTrust.
URL for testing:
- https://harden-onetrust-check--helix-rum-enhancer--adobe.aem.page/
#415 
> fix: check for OneTrust PC sdk if banner is not present

- plugins/a11y.js
- test/it/a11y.audience.medium-zoom.test.html
- test/it/a11y.audience.zoom.test.html
- test/it/broken-plugin.test.html
- test/it/index.test.html
- test/it/navigation.test.html
- test/it/size.test.html
Turns out the initial PR have a few flaws:
1. Tracking dark theme as an accessibility feature is a bad idea… our data shows that a lot of users have it enabled on some sites
2. The coarse pointer logic was reversed
> fix(a11y): audience is flagged as using accessibility too often

- plugins/a11y.js
- test/it/a11y.audience.high.test.html
- test/it/a11y.audience.hover.test.html
- test/it/a11y.audience.medium-zoom.test.html
- test/it/a11y.audience.preference.test.html
- test/it/a11y.audience.zoom.test.html
This pull request overhauls the accessibility audience detection plugin to provide more granular and actionable insights into user needs. The previous binary (`on`/`off`) reporting has been replaced with a weighted scoring system that categorizes users into one of four audience segments: `off`, `low`, `medium`, or `high`. It loosely follows the A/AA/AAA levels.
- *Weighted Scoring System*: Introduced a scoring model inspired by WCAG conformance levels (`A_WEIGHT`, `AA_WEIGHT`, `AAA_WEIGHT`) to give more significance to stronger accessibility signals.
- **Granular Audience Reporting**: The sampleRUM event for the a11y checkpoint now reports a `source` of `off`, `low`, `medium`, or `high`, providing a clearer picture of the user's potential needs.
- **Expanded Signal Detection**: The …
> feat(a11y): introduce granular a11y level detection

- modules/index.js
Tests in other repos are actually explicitly checking for `initEnhancer` and we inadvertently lost this recently.
See: https://github.com/adobe/helix-rum-collector/actions/runs/16274260050
> fix: initialization logic
